project_id = "hlpdowxuscszkonsfccq"

[functions.extract-report]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.create-doctor]
verify_jwt = false

[functions.update-doctor]
verify_jwt = false

[functions.generate-risk-explanation]
verify_jwt = false

[functions.analyze-video]
verify_jwt = false
